"""
train_llama.py
--------------
QLoRA fine-tuning of meta-llama/Meta-Llama-3.1-8B-Instruct on the CTA advisory
dataset generated by scripts/generate_llama_data.py.

Uses Unsloth for 2x faster training + reduced VRAM via patched attention kernels.
Adapter weights are saved to models/llama_cta_adapter/ in HF format so they can
be loaded at inference time with a single from_pretrained call.

Requirements:
    - GPU with ≥16 GB VRAM (A10G, A100, RTX 3090/4090) or Colab A100
    - HF_TOKEN env var set (Llama 3.1 is gated)
    - data/llama_train.jsonl from generate_llama_data.py

Run:
    python src/train_llama.py
    python src/train_llama.py --epochs 3 --batch 4 --output models/my_adapter
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ── HF token must be set before any transformers import ──────────────────────
from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env")
hf_token = os.getenv("HF_TOKEN")
if not hf_token:
    print("[train] WARNING: HF_TOKEN not set. Llama 3.1 is gated — download will fail.")
else:
    os.environ["HUGGING_FACE_HUB_TOKEN"] = hf_token

# ── Unsloth must be imported before transformers/peft ────────────────────────
try:
    from unsloth import FastLanguageModel
    UNSLOTH_AVAILABLE = True
except ImportError:
    UNSLOTH_AVAILABLE = False
    print("[train] WARNING: Unsloth not installed. Falling back to standard PEFT/transformers.")
    print("        Install with: pip install unsloth[colab-new]")

import torch
from datasets import load_dataset
from transformers import TrainingArguments
from trl import SFTTrainer


# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).parent.parent

DEFAULTS = dict(
    base_model    = os.getenv("BASE_MODEL_ID", "meta-llama/Meta-Llama-3.1-8B-Instruct"),
    data_path     = str(ROOT / "data" / "llama_train.jsonl"),
    output_dir    = os.getenv("LLAMA_ADAPTER_PATH", str(ROOT / "models" / "llama_cta_adapter")),
    max_seq_len   = 512,
    # QLoRA hyperparameters
    lora_r        = 16,    # rank — higher = more capacity, more VRAM
    lora_alpha    = 32,    # LoRA scaling factor (typically 2x rank)
    lora_dropout  = 0.05,
    # Training hyperparameters
    epochs        = 3,
    batch_size    = 2,
    grad_accum    = 4,     # effective batch = batch_size * grad_accum = 8
    lr            = 2e-4,
    warmup_ratio  = 0.05,
    weight_decay  = 0.01,
    # Quantisation
    load_in_4bit  = True,
)

# Llama 3.1 chat template tokens
EOS_TOKEN = "<|eot_id|>"

# Target modules for LoRA (which weight matrices to adapt)
LORA_TARGET_MODULES = [
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj",
]


# ─────────────────────────────────────────────────────────────────────────────
# Dataset formatting
# ─────────────────────────────────────────────────────────────────────────────
def apply_chat_template(sample: dict, tokenizer) -> dict:
    """
    Converts our JSONL messages list into the Llama 3.1 instruction template string.
    The EOS token is appended so the model learns when to stop generating.
    """
    text = tokenizer.apply_chat_template(
        sample["messages"],
        tokenize=False,
        add_generation_prompt=False,
    )
    return {"text": text + EOS_TOKEN}


# ─────────────────────────────────────────────────────────────────────────────
# Model loader
# ─────────────────────────────────────────────────────────────────────────────
def load_model_and_tokenizer(cfg: dict):
    """
    Loads base model + tokenizer. Uses Unsloth if available (faster + less VRAM),
    otherwise falls back to standard Hugging Face + PEFT.
    """
    if UNSLOTH_AVAILABLE:
        print(f"[train] Loading {cfg['base_model']} via Unsloth (4-bit: {cfg['load_in_4bit']}) …")
        model, tokenizer = FastLanguageModel.from_pretrained(
            model_name    = cfg["base_model"],
            max_seq_length= cfg["max_seq_len"],
            dtype         = None,           # auto-detect (bfloat16 on Ampere+)
            load_in_4bit  = cfg["load_in_4bit"],
            token         = hf_token,
        )

        model = FastLanguageModel.get_peft_model(
            model,
            r                  = cfg["lora_r"],
            target_modules     = LORA_TARGET_MODULES,
            lora_alpha         = cfg["lora_alpha"],
            lora_dropout       = cfg["lora_dropout"],
            bias               = "none",
            use_gradient_checkpointing = "unsloth",  # Unsloth's memory-efficient checkpointing
            random_state       = 42,
            use_rslora         = False,
        )

    else:
        # Standard HF path (no Unsloth optimisations)
        from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
        from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

        print(f"[train] Loading {cfg['base_model']} via transformers+PEFT …")
        bnb_config = BitsAndBytesConfig(
            load_in_4bit              = cfg["load_in_4bit"],
            bnb_4bit_quant_type       = "nf4",
            bnb_4bit_compute_dtype    = torch.bfloat16,
            bnb_4bit_use_double_quant = True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            cfg["base_model"],
            quantization_config = bnb_config,
            device_map          = "auto",
            token               = hf_token,
        )
        tokenizer = AutoTokenizer.from_pretrained(cfg["base_model"], token=hf_token)
        model = prepare_model_for_kbit_training(model)

        lora_config = LoraConfig(
            r              = cfg["lora_r"],
            lora_alpha     = cfg["lora_alpha"],
            target_modules = LORA_TARGET_MODULES,
            lora_dropout   = cfg["lora_dropout"],
            bias           = "none",
            task_type      = "CAUSAL_LM",
        )
        model = get_peft_model(model, lora_config)

    # Llama 3.1 uses right-side padding for batch training
    tokenizer.padding_side = "right"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    return model, tokenizer


# ─────────────────────────────────────────────────────────────────────────────
# Training
# ─────────────────────────────────────────────────────────────────────────────
def train(cfg: dict) -> None:
    # Verify data exists
    data_path = Path(cfg["data_path"])
    if not data_path.exists():
        print(f"[train] ERROR: Training data not found at {data_path}")
        print("        Run: python scripts/generate_llama_data.py")
        sys.exit(1)

    print(f"[train] Loading dataset from {data_path} …")
    raw = load_dataset("json", data_files=str(data_path), split="train")
    print(f"[train] {len(raw)} training examples")

    # Load model
    model, tokenizer = load_model_and_tokenizer(cfg)

    # Apply chat template to each example
    dataset = raw.map(
        lambda x: apply_chat_template(x, tokenizer),
        remove_columns=raw.column_names,
    )

    # Print trainable parameter count
    if UNSLOTH_AVAILABLE:
        model.print_trainable_parameters()
    else:
        trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
        total     = sum(p.numel() for p in model.parameters())
        print(f"[train] Trainable: {trainable:,} / {total:,} ({100*trainable/total:.2f}%)")

    # Training arguments
    training_args = TrainingArguments(
        output_dir                  = cfg["output_dir"],
        num_train_epochs            = cfg["epochs"],
        per_device_train_batch_size = cfg["batch_size"],
        gradient_accumulation_steps = cfg["grad_accum"],
        warmup_ratio                = cfg["warmup_ratio"],
        learning_rate               = cfg["lr"],
        weight_decay                = cfg["weight_decay"],
        fp16                        = not torch.cuda.is_bf16_supported(),
        bf16                        = torch.cuda.is_bf16_supported(),
        logging_steps               = 10,
        save_strategy               = "epoch",
        save_total_limit            = 2,
        optim                       = "adamw_8bit" if UNSLOTH_AVAILABLE else "adamw_torch",
        lr_scheduler_type           = "cosine",
        report_to                   = "none",   # set to "wandb" if you want tracking
        seed                        = 42,
    )

    # SFTTrainer handles tokenisation, packing, and the training loop
    trainer = SFTTrainer(
        model            = model,
        tokenizer        = tokenizer,
        train_dataset    = dataset,
        dataset_text_field = "text",
        max_seq_length   = cfg["max_seq_len"],
        dataset_num_proc = 2,
        packing          = True,   # pack short sequences for GPU efficiency
        args             = training_args,
    )

    # ── Train ─────────────────────────────────────────────────────────────────
    print("\n[train] Starting fine-tuning …")
    trainer_stats = trainer.train()

    train_loss = trainer_stats.training_loss
    runtime    = trainer_stats.metrics.get("train_runtime", 0)
    print(f"\n[train] Done. Final loss: {train_loss:.4f}  |  Runtime: {runtime:.0f}s")

    # ── Save adapter only (not full model — much smaller) ────────────────────
    out = Path(cfg["output_dir"])
    out.mkdir(parents=True, exist_ok=True)

    if UNSLOTH_AVAILABLE:
        model.save_pretrained(str(out))
        tokenizer.save_pretrained(str(out))
    else:
        model.save_pretrained(str(out))
        tokenizer.save_pretrained(str(out))

    print(f"[train] Adapter saved → {out}")
    print(f"        Load at inference: FastLanguageModel.from_pretrained('{out}')")


# ─────────────────────────────────────────────────────────────────────────────
# Inference helper  (used by app.py)
# ─────────────────────────────────────────────────────────────────────────────
def load_for_inference(adapter_path: str, base_model: str | None = None, max_seq_len: int = 512):
    """
    Loads the fine-tuned adapter for streaming inference.
    Returns (model, tokenizer) ready for generation.

    Usage in app.py:
        model, tokenizer = load_for_inference("models/llama_cta_adapter")
        FastLanguageModel.for_inference(model)  # enables 2x faster generation
    """
    if not UNSLOTH_AVAILABLE:
        raise RuntimeError("Unsloth required for inference. pip install unsloth[colab-new]")

    resolved_base = base_model or os.getenv("BASE_MODEL_ID", DEFAULTS["base_model"])

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name    = adapter_path,
        max_seq_length= max_seq_len,
        dtype         = None,
        load_in_4bit  = True,
        token         = hf_token,
    )
    FastLanguageModel.for_inference(model)
    return model, tokenizer


def generate_advisory(model, tokenizer, user_prompt: str, max_new_tokens: int = 200) -> str:
    """
    Generates a single CTA advisory from a user prompt string.
    Expects the caller to have called load_for_inference() first.
    """
    from unsloth import FastLanguageModel

    system_msg = (
        "You are the CTA Transit Assistant — a no-nonsense Chicago transit advisor "
        "embedded in the city's Intelligent Transit System. "
        "You speak like a knowledgeable Chicago local: direct, practical, and familiar "
        "with the city's neighborhoods, sports teams, weather patterns, and the quirks of the 'L'. "
        "Given a model prediction about transit conditions, provide a concise, actionable advisory. "
        "Include the delay estimate, the primary cause, and what the rider should do. "
        "Keep it under four sentences."
    )

    messages = [
        {"role": "system",    "content": system_msg},
        {"role": "user",      "content": user_prompt},
    ]
    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            input_ids      = inputs,
            max_new_tokens = max_new_tokens,
            use_cache      = True,
            temperature    = 0.7,
            top_p          = 0.9,
            do_sample      = True,
        )

    # Decode only the newly generated tokens
    new_tokens = outputs[0][inputs.shape[-1]:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True).strip()


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fine-tune Llama 3.1 on CTA advisory data")
    parser.add_argument("--base",    default=DEFAULTS["base_model"],  help="Base HF model ID")
    parser.add_argument("--data",    default=DEFAULTS["data_path"],   help="Path to llama_train.jsonl")
    parser.add_argument("--output",  default=DEFAULTS["output_dir"],  help="Adapter output directory")
    parser.add_argument("--epochs",  type=int,   default=DEFAULTS["epochs"],     help="Training epochs")
    parser.add_argument("--batch",   type=int,   default=DEFAULTS["batch_size"], help="Per-device batch size")
    parser.add_argument("--lr",      type=float, default=DEFAULTS["lr"],         help="Learning rate")
    parser.add_argument("--lora-r",  type=int,   default=DEFAULTS["lora_r"],     help="LoRA rank")
    parser.add_argument("--no-4bit", action="store_true",  help="Disable 4-bit quantisation")
    args = parser.parse_args()

    cfg = {**DEFAULTS}
    cfg.update({
        "base_model":  args.base,
        "data_path":   args.data,
        "output_dir":  args.output,
        "epochs":      args.epochs,
        "batch_size":  args.batch,
        "lr":          args.lr,
        "lora_r":      args.lora_r,
        "load_in_4bit":not args.no_4bit,
    })

    train(cfg)
